stages:
  - build
  - python_script

default:
  artifacts:
    expire_in: 3 days

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH
  only: [branches]
    changes: [Dockerfile, requirements.txt]

process_files:
  stage: python_script
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH
  script:
    - python3 figshareFeedProcessor.py
  artifacts:
    paths:
      - hrfeed.xml
      - uniqdeptmsg.txt
  only: [schedules]
